<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [19]:
def matrix_mul(A, B):
    #condition to check for posibility of matrix multiplication
    if len(A[0])==len(B):
        mul_A_B = [] #to store matrix(A)*matrix(B)
        for i in range(len(A)):
            mul = []#to temporarily store individual rows 
            for j in range(len(B[0])):
                m = 0 #to temporarily store inidividual elements of multiplication
                for k in range(len(A[0])):
                    m+=(A[i][k]*B[k][j]) #matrix multiplication
                #appending elements to list
                mul.append(m)
            mul_A_B.append(mul)
        return mul_A_B
    else:
        print("Matrix multiplication not possible")
    

A =[[1,2],[3,4]]
B =[[1,2,3,4,5],[5,6,7,8,9]]
matrix_mul(A, B)

[[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]]

<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [60]:
from random import uniform
def pick_a_number_from_list(A):
    Sum = 0
    cumulative_lst = []
    #finding cumulative sum of the given list
    for num in A:
        Sum +=num
        cumulative_lst.append(Sum)
    p = int(uniform(0,Sum))
    #using uniform function we pick any number between 0 and Sum
    for i in range(len(A)):
        #here based on the magnitude or the range based on cumulative sum a number is picked and returned
        if (p>=cumulative_lst[i] and p<cumulative_lst[i+1]):
            return A[i+1]
    return 0


def sampling_based_on_magnitued(A):
    count = {}
    #for selecting an element and repeating it 100 times
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number)
        #printing the number which is being picked and finding the count to know no. of times it is picked
        if number in count:
            count[number]+=1
        else:
            count[number]=1
    return A,count
    
A = [0,5,27,6,13,28,100,45,10,79]
#pick_a_number_from_list(A)
sampling_based_on_magnitued(A)

79
28
100
79
100
79
100
100
27
79
5
45
100
45
13
10
6
28
100
28
100
100
100
100
79
79
27
79
45
45
79
13
10
100
100
100
100
28
28
79
100
100
28
28
45
28
45
45
28
79
100
28
79
45
28
27
27
28
13
79
28
45
100
100
100
45
10
100
100
79
45
100
79
28
45
45
79
45
79
100
100
100
100
13
79
100
100
100
100
45
100
100
100
100
100
79
13
100
79


([0, 5, 27, 6, 13, 28, 100, 45, 10, 79],
 {79: 19, 28: 14, 100: 37, 27: 4, 5: 1, 45: 15, 13: 5, 10: 3, 6: 1})

<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [53]:
import re
def replace_digits(String):
    String = re.sub('#',"",String)
    #since '#' is used to comment first we will remove it from the given string if it is present
    for i in String:
        #using for loop to iterate and replace digits with "#" and remove non digits
        if i in "0123456789":
            String = String.replace(i,"#")
        else:
            String = String.replace(i,"")
        
    return String # modified string which is after replacing the # with digits

String = "#2a$#b%c%561#"
replace_digits(String)

'####'

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [81]:
def display_dash_board(students, marks):
    l = len(marks)
    #creating a dictionary of marks & students
    dict = {marks[i]:students[i] for i in range(l)}
    print(dict)
    #create a sorted list of marks in descending order 
    sort_dict=sorted(dict.keys(),reverse= True)
    print("a. Who got top 5 ranks, in the descending order of marks")
    for i in range(5):
        #printing top five students with their marks
        print(dict[sort_dict[i]]+" ",sort_dict[i])
        
    print("b. Who got least 5 ranks, in the increasing order of marks") 
    #create a sorted list of marks in ascending order
    sort_dict_Asc=sorted(dict.keys())
    for i in range(5):
        #printing least five students with their marks
        print(dict[sort_dict_Asc[i]]+" ",sort_dict_Asc[i])
    
    print("d. Who got marks between >25th percentile <75th percentile, in the increasing order of marks")
    for i in range(int(0.25*l),int(.75*l)):
        #using ascending ordered sorted list to find stidents between 25 and 75 percentile
        print(dict[sort_dict_Asc[i]]+" ",sort_dict_Asc[i])
    

students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10']
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
display_dash_board(students,Marks)

{45: 'student1', 78: 'student2', 12: 'student3', 14: 'student4', 48: 'student5', 43: 'student6', 47: 'student7', 98: 'student8', 35: 'student9', 80: 'student10'}
a. Who got top 5 ranks, in the descending order of marks
student8  98
student10  80
student2  78
student5  48
student7  47
b. Who got least 5 ranks, in the increasing order of marks
student3  12
student4  14
student9  35
student6  43
student1  45
d. Who got marks between >25th percentile <75th percentile, in the increasing order of marks
student9  35
student6  43
student1  45
student7  47
student5  48


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [94]:
import math
def closest_points_to_p(S, P):
    lst_dist = {}#initialize empty dictionary to store distance and points
    for point in S:
        #finding distance from the point to every point in the list S and adding to dictionary
        num = (P[0]*point[0])+(P[1]*point[1])
        den = math.sqrt((P[0]**2+P[1]**2)*(point[0]**2+point[1]**2))
        dist = math.acos(num/den)
        lst_dist[dist]=point
    #finding the points with least distance using sorted function
    fin = sorted(lst_dist.keys())[:5]
    fin_lst = [lst_dist[i] for i in fin]   
    return fin_lst# its list of tuples

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
lst_points = closest_points_to_p(S, P)
print("Five Closest points to point P:{} are:".format(P))
for i in lst_points:
    print(i)

Five Closest points to point P:(3, -4) are:
(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [88]:
import math
def i_am_the_one(red,blue,line):
    
    # using eval fuction to evaluate the line fuction for any one point
    red_sign = eval(line.replace('x',"*%s"%red[0][0]).replace('y',"*%s"%red[0][1]))
    blue_sign = eval(line.replace('x',"*%s"%blue[0][0]).replace('y',"*%s"%blue[0][1]))
    
    # checking condition that if either both are positive or negative i.e. on the same side of the line
    if (red_sign>0 and blue_sign>0)or(red_sign<0 and blue_sign<0):
        return "NO"
    
    # if false we then check all the points of same colour are on the same side or different
    else:
        
        # checking red points
        for i in red:
            r_check = eval(line.replace('x',"*%s"%i[0]).replace('y',"*%s"%i[1]))
            if (red_sign>0 and r_check>0)or(red_sign<0 and r_check<0):
                continue
            else:
                return "N0"
            
        # checking blue points
        for j in blue:
            b_check = eval(line.replace('x',"*%s"%j[0]).replace('y',"*%s"%j[1]))
            if (blue_sign>0 and b_check>0)or(blue_sign<0 and b_check<0):
                continue
            else:
                return "N0"
    # if all points of red lies one side and blue on other return YES
    return "YES"

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

YES
N0
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [16]:
# takes an array x and two indices a,b. 
# Replaces all the _'s with (x[a]+x[b])/(b-a+1)
def fun(x, a, b):
    if a == -1:
        v = float(x[b])/(b+1)
        for i in range(a+1,b+1):
            x[i] = v
    elif b == -1:
        v = float(x[a])/(len(x)-a)
        for i in range(a, len(x)):
            x[i] = v
    else:
        v = (float(x[a])+float(x[b]))/(b-a+1)
        for i in range(a,b+1):
            x[i] = v
    return x

def replace(text):
    # Create array from the string
    x = text.replace(" ","").split(",")
    # Get all the pairs of indices having number
    y = [i for i, v in enumerate(x) if v != '_']
    # Starting with _ ?
    if y[0] != 0:
        y = [-1] + y
    # Ending with _ ?
    if y[-1] != len(x)-1:
        y = y + [-1]    
    # run over all the pairs
    for (a, b) in zip(y[:-1], y[1:]): 
        fun(x,a,b)          
    return x


 
S=  "_,_,30,_,_,_,50,_,_"
replace(S)

[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]

<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [8]:
def compute_conditional_probabilites(A):
    f_dict = {}#initailizing dictionary for F unique values
    s_dict = {'S1':0,'S2':0,'S3':0}#initailizing dictionary for S unique values
    
    #looping over A to store F values as key and values initialized to 0
    for i in A:
        a_key = i[0]+i[1]
        f_dict[a_key] = 0
    
    # looping over A to find intersection between f_dict & A
    # and s_dict & A
    # and incrementing values in dictionary
    for j in A:
        a_key = j[0]+j[1]
        f_dict[a_key]+=1
        
        s_key = j[1]
        s_dict[s_key]+=1
    
    # finally using above values in dictionary print conditonal probabilities as shown in above cell
    for n in range(1,6):
        a = "F"+str(n)+"S1"
        b = "F"+str(n)+"S2"
        c = "F"+str(n)+"S3"
        print("P(F=F{0}|S==S1)={1}/{2}, P(F=F{0}|S==S1)={3}/{4}, P(F=F{0}|S==S1)={5}/{6}"
              .format(n,f_dict.get(a,0),s_dict.get('S1'),
                     f_dict.get(b,0),s_dict.get('S2'),
                     f_dict.get(c,0),s_dict.get('S3')))
        
    

            
        
    # print the output as per the instructions

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

P(F=F1|S==S1)=1/4, P(F=F1|S==S1)=1/3, P(F=F1|S==S1)=0/3
P(F=F2|S==S1)=1/4, P(F=F2|S==S1)=1/3, P(F=F2|S==S1)=1/3
P(F=F3|S==S1)=0/4, P(F=F3|S==S1)=1/3, P(F=F3|S==S1)=1/3
P(F=F4|S==S1)=1/4, P(F=F4|S==S1)=0/3, P(F=F4|S==S1)=1/3
P(F=F5|S==S1)=1/4, P(F=F5|S==S1)=0/3, P(F=F5|S==S1)=0/3


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [92]:
def string_features(S1, S2):
    # using split function to create a list of space separated words of both S1 & S2
    S1 = set(S1.split(" "))
    S2 = set(S2.split(" "))
    #using intersection method of sets to find commom elemnets between S1 & S2
    a = len(S1.intersection(S2))
    #using difference method of sets to find elemnets present in S1 & not in S2
    b = S1.difference(S2)
    #using difference method of sets to find elemnets present in S2 & not in S1
    c = S2.difference(S1)
    return a,b,c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print("a. Number of common words between S1, S2: ",a)
print("b. Words in S1 but not in S2: ",list(b))
print("c. Words in S2 but not in S1: ",list(c))



a. Number of common words between S1, S2:  7
b. Words in S1 but not in S2:  ['5', 'first', 'F']
c. Words in S2 but not in S1:  ['3', 'S', 'second']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [106]:
from math import log10

def compute_log_loss(A):
    n = len(A)
    log_sum = 0
    #for loop to implement summation as in above formula
    for p in A:
        log_sum += (p[0]*log10(p[1]))+((1-p[0])*log10(1-p[1]))
    loss = -1*(1/n)*log_sum
    
    return loss #return the function output

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print("loss:{:.7f}".format(loss))

loss:0.4243099
